### ISSUE TITLE
signup: take debank.com "total amont"

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/onout_dashboard#12]
у debank.com есть апи по которому можно чекнуть примерно сколько у адреса денег, желательно его использовать, чтоб заполнять соответсвующее поле при логине

**Comment by VitaliyShulik** [comment]
Только при регистрации проверять или при каждом логине тоже?

**Comment by VitaliyShulik** [comment]
https://github.com/noxonsu/onout_back/pull/4

**Comment by VitaliyShulik** [comment]
В общем теперь если нет баланса или приходит ошибка устанавливается 0 баланс + все юзеры добавляются в onout.org list в сендгриде
