### ISSUE TITLE
email subscription doesn't work

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/onout_dashboard#2]
я залогинился под своим кошельком, ввел емейл, перезагрузил страницу и 

- [x] почемуто я разлогинился
- [x] после повторного логина опять показало введите емейл

**Comment by VitaliyShulik** [comment]
1) Нужно будет в локалсторедж добавит то что ты был авторизирован и через что - после перезагрузки можно будет проверять это и коннектиться снова
2) По поводу "после повторного логина опять показало введите емейл" - не смог воспроизвести, все работает норм...

**Comment by NotEternal** [comment]
> 1. Нужно будет в локалсторедж добавит то что ты был авторизирован и через что - после перезагрузки можно будет проверять это и коннектиться снова
> 2. По поводу "после повторного логина опять показало введите емейл" - не смог воспроизвести, все работает норм...

та же тема. Я ввожу адрес и после подписки вижу продукты. Разлогиниваюсь и снова захожу, вижу форму. Перезагружаюсь, логинюсь и вижу форму. Спустя пару минут (может быстрее), пока я думал, получилось норм зайти. Видимо это из-за задержки в Sendgrid

**Comment by noxonsu** [comment]
- [ ] я не вижу в сендгриде емейлы которые ввожу!

**Comment by noxonsu** [comment]
да в сенгрид не сразу попадает
