### ISSUE TITLE
Fix switching between networks

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/onout_dashboard#46]
When a user switches from the wrong network to the right one:

![image](https://user-images.githubusercontent.com/61930014/157196695-59314861-66cd-44d4-aba6-6dd0b6fe00b5.png)

**Comment by VitaliyShulik** [comment]
It works with internal Ethereum mainnet chain. I think it happens when connecting to an external chain, 'cause the Metamask uses an async function for it...
